zenhack/simp_le

setup.py
simp_le.py

Acme 0.15.0 throws an `errors.ConflictError` with the uri of the already registered account instead of a `messages.Error` containing the response json. This was introduced in: certbot/certbot@10bac10.
I am not sure if you want to raise the required acme version yet, but as I am using arch linux, which already provides acme 0.15, I thought this might be useful. I am also not sure if these are *all* the required changes for the new acme version, but at least all my cert-updates went through successfully.

Support for acme 0.15

---

.travis.yml

Python 3.3 builds are failing : https://travis-ci.org/buchdag/simp_le/builds/261004728
Fix is similar to e6864f6

Fix CI breakage for python 3.3

---

simp_le.py

This PR disable self-verification by default and make it available via a new `--self_verify` argument.
Reason for disabling it is that [it is considered unreliable by certbot devs themselves](https://github.com/certbot/certbot/issues/1586#issuecomment-186020863).
I witnessed with [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) that indeed quite often the self verification fails while the CA challenge validation succeed, [making people search for a non existent issue](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/234). Plus the self-verification has little troubleshooting value, in verbose mode you just get the result of the failed GET request.

Remove self-verification

---

simp_le.py

This PR aims to provide basic sanitization for domain names: 
- domains are converted to lowercase (fix for #25)
- raise an error if utf-8 characters are used, as LE does not directly support them
The utf-8 check is currently causing an unexpected doctest error on python 2.6 but not on 2.7, I haven't found a solution yet, any help is welcome:
```
ERROR: Doctest: simp_le.Vhost.decode
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/python/2.6.9/lib/python2.6/doctest.py", line 2158, in runTest
test, out=new.write, clear_globs=False)
File "/opt/python/2.6.9/lib/python2.6/doctest.py", line 1391, in run
return self.__run(test, compileflags, out)
File "/opt/python/2.6.9/lib/python2.6/doctest.py", line 1277, in __run
got += …
```

Add basic domains sanitization to Vhost.decode()

---

.travis.yml
README.rst
docker/Dockerfile
docker/Dockerfile.localbuild
docker/README.md
docker/entrypoint.sh
tests/install.sh
tests/test-suite.sh

This PR add Docker support to the project and the relevant Travis tests.
The image is based on Alpine linux 3.6 with Python 3 and weight ~ 85MB
The following:
```
services:
- docker
```
has been removed from the travis.yml file as [it isn't needed anymore with the Travis Trusty build environment](https://docs.travis-ci.com/user/reference/trusty/#Docker) and triggered a warning message.

Add Docker support

---

README.rst
simp_le.py

Proposed fix for #5 
Not much to add, the challenge validation files are one shot so they're removed wether the validation succeed or fail.

Cleanup challenge files after use

---

simp_le.py

W0511 on line 185 triggered by # XXX
W1505 deprecated warn() on line 1061

Fix two pylint warning

---

docker/README.md

I feel it's easier to parse this way.
Also fixed a typo on an `--email` missing a `-` and added a link to nginx official docker image.

Split example Docker commands on multiple lines

---

simp_le.py

Quick and dirty fix for #85 
As @cpu mentioned, the LE ToS hash should not be hardcoded but retrieved from LE ACME API endpoint, I'll see if I can handle this.

Quick fix for LE ToS nov 2017 update

---

simp_le.py

Caught the deprecation warning some time ago while running tests but I wasn't sure it should be removed. Thanks to @bmw for explaining it to me in details
https://letsencrypt.readthedocs.io/projects/acme/en/latest/api/client.html#acme.client.Client.request_challenges
certbot/certbot#4303

Remove deprecated new_authz_uri from chall request

---

simp_le.py

This  PR correct three careless mistakes on #88 ( `,` instead of ` %` on `Error()` string formatting ).

Fix string formatting on errors

---

simp_le.py

This a first take at what's been discussed on #23 
730831b just reorder plugins and unit test classes to something a bit more readable and logical to me. There is zero code change on this commit.
3f11801 change the `AccountKey()` `KeyFile()` `CertFile()` `ChainFile()` `FullChainFile()` and `FullFile()` IOPlugins classes to be more similar. `FullChainFile()` is no longer a subclass of `ChainFile()`. The 3 "chain" plugins use a list built from the iterator created by `split_pems()` to allow testing its length (required to catch issues with those files later).
e078cee `split_pems()` is only used by subclasses of `OpenSSLIOPlugin()` so it make more sense to me to make it a method of this class rather than a function. The test performed by the function doctest has been moved to the unit test …

Empty or corrupt files detection and error + code cleanup

---

.travis.yml
docker/Dockerfile
docker/hooks/build
docker/hooks/post_push
docker/hooks/push
tests/install.sh
tests/test-suite.sh

This PR is a continuation of #98 and brings tests and automated Docker builds for `arm` and `arm64` archs in addition to `x86_64`/`amd64`, plus the automated creation and push of a [Docker manifest](https://blog.docker.com/2017/11/multi-arch-all-the-things/).
The use of a Docker manifest mean that when you do `docker pull zenhack/simp_le` on one of the supported archs, Docker will automatically pull the correct layers for the archs it's running on. It's completely transparent for the user and most of the core images now support multiarch this way (vs previously having separate repos for other archs, like `arm32v6/alpine`).
This step is currently done with [Phil Estes's Manifest Tool](https://github.com/estesp/manifest-tool). This tool will be merged to the Docker CLI in a future version …

Docker multiarch support

---

.travis.yml
README.rst
setup.py
simp_le.py

A few more changes than usual:
- acme.jose has been moved to a separate package named [josepy](https://github.com/certbot/josepy)
- python 2.6 is being deprecated by acme like 3.3 was last year

Update ACME to 0.21

---

setup.py

requests seems to be ok with idna 2.7 now https://github.com/requests/requests/blob/master/setup.py#L53

Raise idna upper bound to <2.8

---

tests/install.sh

Boulder master is currently broken on Docker : https://github.com/letsencrypt/boulder/issues/4284
This PR use the last tag before the commit that introduced that issue, instead of the `master` branch.

Fix CI breakage due to Boulder

---

README.rst
simp_le.py

This fix an issue that came to light while trying to switch the test suite from `boulder` to `pebble`.
While the previous code worked with current `boulder` version, it's actually not ACME v2 compliant and caused POST-as-GET errors with Pebble. That indicates potential real world breakage starting November 1st when POST-as-GET becomes mandatory : https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

Fix ACME v2 client registration

---

.travis.yml
simp_le.py
tests/install.sh
tests/test-suite.sh

As discussed in #123, this PR runs integration tests against Pebble rather than Boulder.
[As suggested by Pebble's doc](https://github.com/letsencrypt/pebble#avoiding-client-https-errors), it adds the following feature to make testing with Pebble possible:
> client should offer a runtime option to specify a list of trusted root CAs
In this PR Pebble does not run in [strict mode](https://github.com/letsencrypt/pebble#strict-mode) because the `acme` Python module around which `simp_le` is built [is not currently compliant with RFC8555](https://github.com/certbot/certbot/issues/7177).
@zenhack If you think we should test against both Pebble and Boulder, let me know.

CI: run tests against pebble

---

bootstrap.sh
venv.sh

Also, completely switch to python3 in bootstrap.sh
v0.15 officially drops support for python2, but most Debian-like LTS-style systems will still have it installed and default to it when using `virtualenv`. This way we can be sure that the provided install path will be running on python3
This PR doesn't address the `yum` world, as python3 doesn't seem to be in core, and I don't have the background to know what the standard install path for it is there.
Also closes #21

Make venv.sh create a python3 virtualenv

---

simp_le.py
tests/install.sh

This PR update the integration test to take into consideration the account registration file.
The integration test now check that the account registration file is correctly recovered if it was removed from the current working directory, and check the account registration file status along with the other files.
The version of Boulder used in the Travis integration test has also been updated to `2019-10-13`.
Does this need to be added to the changelog too ?

Account registration test updates

---

simp_le.py

This should fix #133. In addition to the tests in the commit I also ran this on the log output @OscarKolsrud sent me. @OscarKolsrud, could you check that this works for you?

split_pems: handle CRLF line endings correctly.

---

simp_le.py
tests/install.sh

Upgrading the test suite's `pebble` to > `v2.1.0` bring the following ACME v2 non conformity into light:
```
2019-10-18 09:02:36,642:DEBUG:acme.client:1102: Sending POST request to https://pebble:14000/chalZ/dXS797Vw4jl-_AckjPSCGdVzibOtsk0tLxVazNEnskE:
{
"protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vcGViYmxlOjE0MDAwL215LWFjY291bnQvMSIsICJub25jZSI6ICJmcW9XMTJkMWlDNndqTjJIMTNqejRBIiwgInVybCI6ICJodHRwczovL3BlYmJsZToxNDAwMC9jaGFsWi9kWFM3OTdWdzRqbC1fQWNralBTQ0dkVnppYk90c2swdEx4VmF6TkVuc2tFIn0",
"signature": "BgnHMJ5vvoA1iMyZfJPwiSoYe8KsYCeVhw9cH27bFlkCknOwbeuf_3Uub67MW5pbzuI7jb6hVLonV9bXkjOQdnXUNnQRYe1SeYzkISNacaHtdhXj8WT2DVcmNo0_frcLn8_AkT6PM00OWu81k5dKDFpVLIdsSB4TQn_M_7Jj_oIJcURBWcXlyoURjBVPmnvMFycws1-O8V5m-ynygbhs-qhaaeUJ5E-4HskCzMN-IDR1dwdVFvzX9mdmbK_jMVL7PYEELZRWdYbOqAnCuWRfl4P …
```

[WIP] Implement authorization polling mechanism

---

simp_le.py

CSRs are PKCS#10 documents, and the standard does not define versions above 0.
Reference: https://github.com/certbot/certbot/pull/9334

Change generated CSR version to 0
