- setup.py
- tox.ini
> Update acme to 0.16

- setup.py
Let's end the day with a version bump.
> Update ACME to 0.17

- README.rst
> Mention default --valid_min in README

- setup.py
> Update ACME to 0.18

- setup.py
ACME 0.18.2 add the patch for #70
> Update ACME to 0.18.2

- simp_le.py
Proposed fix for #16 
With this fix:
- failed authorization result in the `account_key.json` file being created anyway
- failed authorization still raise an error
- `IntegrationTests` test this by attempting a first cert creation with a wrong webroot
> Persist account_key even if authorization fail

- setup.py
> Update ACME to 0.19

- simp_le.py
Cleaned up #87 after a git mishap.
> As suggested by @cpu on #85, this PR aims to get the Let's Encrypt Terms of Service hash at runtime instead of hardcoding it. This will avoid future breakage on ToS change.
Thanks to @lopter for modification suggestions on the original PR.
> Get LE ToS hash from ACME API endpoint

- setup.py
- simp_le.py
PR for basic email validation as discussed on #76 + bump to ACME 0.20
> Validate email address

- README.rst
- setup.py
- simp_le.py
PR N°100 and last PR of 2017 🎉 
Fix #95 by removing ToS hash related code and agreeing automatically to the ToS. This has the nice side effect of removing `requests` from the required modules.
As usual my english wording / grammar is probably not perfect.
> Automatic agreement to ToS (fixes 

- README.rst
- setup.py
Version 0.22 has ACME v2 support merged in, so we can start working on this.
> Update ACME to 0.22

- README.rst
- setup.py
> Update ACME to 0.23

- README.rst
- setup.py
> Update ACME to 0.24

- README.rst
- setup.py
> Update ACME to 0.25

- README.rst
- setup.py
> Update ACME to 0.26

- README.rst
- setup.py
> Update ACME to 0.29

- README.rst
- setup.py
> Update ACME to 0.33

- README.rst
- setup.py
> Update ACME to 0.35

- setup.py
> Upgrade ACME to 1.2

- setup.py
- simp_le.py
If non-zero, then use alternative certificate chain number.
> Add option: --use_alt_chain CHAIN_NO (default: 0)
